project:
  type: website
  output-dir: docs

website:
  title: "Xueqian Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd


format:
  html:
    theme:
      - cosmo
      - brand.scss
    css: styles.css
    toc: false



