---
title: "Research"
---

## Publications

**Chen, Xueqian** (2024). [The Gendered Division of Housework in China: Parenthood Effects and Heterogeneity Across Parenthood Stages.](https://doi.org/10.1007/s11113-024-09872-9) *Population Research and Policy Review*. 43(2), 1–33.

- 2024 Elizabeth Menaghan Award, Department of Sociology, the Ohio State University.


Hui Wang, Yanhui Zou, Hongyan Liu, & **Chen, Xueqian** (2023). [Analysis of unintended pregnancy and influencing factors among married women in China.](https://doi.org/10.1007/s42379-023-00126-3) *China Population and Development Studies*, 1–22.



## Working Papers

**Chen, Xueqian**, "Reassessing the Gendered Link Between Maternal Employment and Adult Children's Labor Market Outcomes: A Trajectory-Based Approach." [[*forthcoming in Social Science Research*]](https://etd.ohiolink.edu/acprod/odb_etd/etd/r/1501/10?clear=10&p10_accession_num=osu173223183180182)

- 2026 Elizabeth Menaghan Award, Department of Sociology, the Ohio State University.

Fangqi Wen, Iani Sam, & **Chen, Xueqian**, "When Little Emperors Grow Up: Intergenerational Support Between Chinese Only Children and Their Parents in Early and Middle Adulthood." [[Under Review]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5669450)

Fangqi Wen, Rui Cao, **Chen, Xueqian**, & Fei Xie, "Can Labor Pain Relief Enhance Childbearing Preferences? Evidence from a Conjoint Experiment in China." [[Under Review]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5841602)
